### ISSUE TITLE
Follow installation steps, but still not working

### ISSUE THREAD

**Issue by tembem** [pebri86/laravel-vue-patternfly#1]
Can you provide more installation steps? Followed the instructions you'd provided, still not work.

**Comment by pebri86** [comment]
Hi, thanks for your interest on the project,
Please tell me the detail problem like some error occured.

Best regards,

**Comment by pebri86** [comment]
Sorry on the description i missed some command, after composer install you should first make and .env file. just do like when you setup regular laravel application. Do this command

```
# cp .env.example .env
# php artisan key:generate
# php artisan jwt:generate
```
Configure your database on .env file then migrate and populate data with seeding. in short just do following command

```
# php artisan migrate
# php artisan db:seed
```

then serve with
```
# php artisan serve
```

Open your browser and access localhost port 8000.
to login as Developer use username : developer@developer.com with password : p@ssw0rd
or as Super Administrator user/pass: superadmin@admin.com/superadmin

Hope that solve your problem, i'll update instruction on the description page.

**Comment by pebri86** [comment]
Is my updated instruction solved your problem? i'll close this issue, 
please reopen if u still face this issue.

thanks,
